wasmx/wasm-chisel

libchisel/src/deployer.rs, libchisel/src/lib.rs, libchisel/src/remapimports.rs, libchisel/src/trimexports.rs, libchisel/src/verifyexports.rs, libchisel/src/verifyimports.rs
This second one returns a module as a result. The original method has been renamed to `translate_inplace`.
Closes #34
=> Implement a non-destructive translate method

libchisel/src/checkstartfunc.rs, libchisel/src/deployer.rs, libchisel/src/lib.rs, libchisel/src/remapimports.rs, libchisel/src/trimexports.rs, libchisel/src/verifyexports.rs, libchisel/src/verifyimports.rs
=> Introduce ModuleError enum for errors 

libchisel/src/lib.rs
In response to https://github.com/wasmx/wasm-chisel/pull/37#discussion_r243587973
=> Implement Display and Error for ModuleError

libchisel/src/imports.rs, libchisel/src/lib.rs, libchisel/src/verifyimports.rs
Depends on #56 
Step 1 of `remapimports` refactor.
=> Split the default ewasm import list out into its own module

libchisel/src/deployer.rs
=> Grow deployer's memory to size

chisel/src/main.rs
If I was using chisel in some kind of build pipeline and module translation resulted in no changes to the wasm, that would currently be interpreted as an error.
=> CLI: return a zero exit code when a module is not modified during translation

README.md, chisel/src/main.rs, libchisel/src/lib.rs, libchisel/src/trimstartfunc.rs
Added code to trim the start function if present.
Here is an example of a chisel.yml using this functionality:
```yaml
ewasm:
file: "build/optimized.wasm"
output: "ewasm_token.wasm"
trimstartfunc:
preset: "ewasm"
```
The preset value is not being used, what would be the right configuration in  `chisel.yml`?
I was thinking something like this:
```yaml
ewasm:
file: "build/optimized.wasm"
output: "ewasm_token.wasm"
trimstartfunc: true
```
@jakelang please take a look and let me know your comments.
=> Module for removing start function (trimstartfunction)

libchisel/src/deployer.rs, libchisel/src/lib.rs
=> Better error handling in transformation modules

README.md, chisel/src/main.rs, libchisel/src/lib.rs, libchisel/src/remapstart.rs
Fixes https://github.com/wasmx/wasm-chisel/issues/99
=> Add support for remapstart

README.md, libchisel/src/dropsection.rs, libchisel/src/lib.rs
=> Introduce dropsection 

libchisel/src/depgraph.rs
Avoids private trait bound on public trait warning, which will be made an error in future rustc releases.
=> Make DepGraphManager and Edge public, prune unused imports in depgraph.rs

.circleci/config.yml, libchisel/Cargo.toml, libchisel/src/fromwat.rs, libchisel/src/lib.rs
Perhaps this has to be a helper instead?
Depends on #108.
=> Introduce FromWat

libchisel/src/checkfloat.rs, libchisel/src/lib.rs
Closes #15 
The following instructions where considered as floating point instructions:
`F32Eq`, `F32Ne`, `F32Lt`, `F32Gt`, `F32Le`, `F32Ge`, `F32Abs`, `F32Neg`, `F32Ceil`, `F32Floor`, `F32Trunc`, `F32Nearest`, `F32Sqrt`, `F32Add`, `F32Sub`, `F32Mul`, `F32Div`, `F32Min`, `F32Max`, `F32Copysign`, `I32TruncSF32`, `I32TruncUF32`, `I64TruncSF32`, `I64TruncUF32`, `F32ConvertSI32`, `F32ConvertUI32`, `F32ConvertSI64`, `F32ConvertUI64`, `F32DemoteF64`, `F64PromoteF32`, `I32ReinterpretF32`, `F32ReinterpretI32`, `F32x4Splat`, `F32x4Eq`, `F32x4Ne`, `F32x4Lt`, `F32x4Le`, `F32x4Gt`, `F32x4Ge`, `F32x4Neg`, `F32x4Abs`, `F32x4Min`, `F32x4Max`, `F32x4Add`, `F32x4Sub`, `F32x4Div`, `F32x4Mul`, `F32x4Sqrt`, `F32x4ConvertSI32x4`, `F32x4ConvertUI32x4`, `I32x4TruncSF32x4Sat`, `I32x4TruncUF32x4Sat`, `F64Eq`, …
=> Add simple floating-point instruction checker.

.gitignore
Tired of having the shell prompt tell me I have untracked files.
Makes it less annoying to prototype the CLI using test wasm files.
=> Ignore .wasm and .wat files in source directories

chisel/Cargo.toml
NOTE: it is called wabt-utils because a feature cannot be named the same as a dependency
=> Properly declare wabt as a feature in CLI

chisel/src/logger.rs, chisel/src/main.rs
Pulled from the CLI rewrite.
Also writes all user-facing messages to stderr, as primary program output goes in stdout (we don't have any as output is written to a file).
NOTE: Yes we are writing debug messages to stderr. The new CLI does this because unix mode will write wasm binaries to stdout unless otherwise specified. Does it matter in this PR? No, it will be overwritten by the other PR anyway.
=> CLI: Introduce logging macro and global log level

chisel/Cargo.toml, chisel/src/main.rs, libchisel/src/lib.rs
Follow up of #154. Also rolls back #150.
=> Remove dependency on parity_wasm from chisel CLI

chisel/src/main.rs
Fixes a bug where the input file would be interpreted as a module configuration.
=> CLI: Require argument delimiters

libchisel/src/trimstartfunc.rs
It only implemented `translate_inplace`. The implementation is the same as in TrimExports.
=> Implement translate() in TrimStartFunc

libchisel/src/deployer.rs
With using the with_data() helper of the builder
=> Simplify create_memory_deployer

libchisel/src/binaryenopt.rs, libchisel/src/checkfloat.rs, libchisel/src/checkstartfunc.rs, libchisel/src/deployer.rs, libchisel/src/dropsection.rs, libchisel/src/lib.rs, libchisel/src/remapimports.rs, libchisel/src/remapstart.rs, libchisel/src/repack.rs, libchisel/src/snip.rs, libchisel/src/trimexports.rs, libchisel/src/trimstartfunc.rs, libchisel/src/verifyexports.rs, libchisel/src/verifyimports.rs
=> Add attempt for better module configuration

chisel/src/driver.rs, libchisel/src/checkfloat.rs, libchisel/src/repack.rs, libchisel/src/snip.rs, libchisel/src/trimexports.rs
Follow up of #161.
Depends on #198.
=> Remove new() from CheckFloat, Repack and Snip
