- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
> Change ModuleTranslator to return whether the module was mutated on success

- README.md
> Document VerifyExports in the README

- chisel/Cargo.toml
- libchisel/Cargo.toml
- libchisel/src/deployer.rs
- libchisel/src/remapimports.rs
- libchisel/src/trimexports.rs
needed to get mutable references to some module sections
> Update to pwasm 0.35

- README.md
- libchisel/src/deployer.rs
> Add ModuleCreator trait on deployer

- README.md
- libchisel/src/lib.rs
- libchisel/src/verifyimports.rs
> Implement VerifyImports

- chisel/Cargo.toml
- libchisel/Cargo.toml
- libchisel/src/deployer.rs
> Use new parity-wasm and CustomSection::new()

- libchisel/src/checkstartfunc.rs
- libchisel/src/deployer.rs
- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
- libchisel/src/trimexports.rs
- libchisel/src/verifyexports.rs
- libchisel/src/verifyimports.rs
This is useful for modules with multiple methods.
> Change module API to not consume self

- libchisel/src/remapimports.rs
> Fix remap list

- libchisel/src/lib.rs
> Fix tests for ModuleTranslator

- README.md
- chisel/Cargo.toml
- chisel/src/main.rs
Implements #26 and #28.
Apparently there is no easy to way to write unit tests for the CLI frontend without things getting ugly and turning `main()` into the call site for the real program main.
Still sort of WIP but also sort of blocked on the actual library getting implemented :trollface:
> CLI frontend for libchisel

- chisel/src/main.rs
- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
- libchisel/src/trimexports.rs
If it returns None that means no changes were made to the input.
> Change ModuleTranslator.translate() to return an Option<Module>

- libchisel/src/verifyimports.rs
> Fix indexing in VerifyImports

- chisel/src/main.rs
> Support multiple rulesets in chisel.yml

- chisel/Cargo.toml
- libchisel/Cargo.toml
This fixes bugs with custom & start sections.
> Upgrade to parity-wasm at least 0.35.6

- README.md
- chisel/src/main.rs
- libchisel/src/lib.rs
- libchisel/src/repack.rs
Inspired by https://github.com/ewasm/sentinel-rs/pull/7 from @cdetrio.
> Introduce repack module

- libchisel/src/deployer.rs
> Use expect instead of unwrap in code

- chisel/src/main.rs
- libchisel/src/dropsection.rs
> Do not use String where not needed

- chisel/src/main.rs
- libchisel/src/depgraph.rs
- libchisel/src/deployer.rs
- libchisel/src/dropsection.rs
- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
- libchisel/src/remapstart.rs
- libchisel/src/repack.rs
- libchisel/src/trimstartfunc.rs
- libchisel/src/utils.rs
- libchisel/src/verifyexports.rs
- libchisel/src/verifyimports.rs
> Remove compiler and clippy warnings

- README.md
- chisel/src/main.rs
- libchisel/Cargo.toml
- libchisel/src/lib.rs
- libchisel/src/snip.rs
Closes #24. Depends on https://github.com/rustwasm/wasm-snip/pull/26.
> Add support for wasm-snip

- libchisel/src/utils.rs
This works with parsed and unparsed NamesSection
> Simplify utils::has_names_section()

- libchisel/src/checkfloat.rs
- libchisel/src/checkstartfunc.rs
- libchisel/src/deployer.rs
- libchisel/src/dropsection.rs
- libchisel/src/fromwat.rs
- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
- libchisel/src/remapstart.rs
- libchisel/src/repack.rs
- libchisel/src/snip.rs
- libchisel/src/trimexports.rs
- libchisel/src/trimstartfunc.rs
- libchisel/src/verifyexports.rs
- libchisel/src/verifyimports.rs
General purpose interface for chisel modules. Needed for CLI refactor.
> Define ChiselModule trait

- chisel/src/main.rs
> CLI: Do not propagate fatal errors when constructing configuration

- chisel/src/main.rs
> CLI: Do not propagate fatal errors in module context builder

- libchisel/src/checkfloat.rs
- libchisel/src/checkstartfunc.rs
- libchisel/src/deployer.rs
- libchisel/src/dropsection.rs
- libchisel/src/fromwat.rs
- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
- libchisel/src/remapstart.rs
- libchisel/src/repack.rs
- libchisel/src/snip.rs
- libchisel/src/trimexports.rs
- libchisel/src/trimstartfunc.rs
- libchisel/src/verifyexports.rs
- libchisel/src/verifyimports.rs
> Add module kind method to ChiselModule

- chisel/src/main.rs
- libchisel/src/deployer.rs
> Change deployer into a ModuleTranslator

- libchisel/src/binaryenopt.rs
- libchisel/src/deployer.rs
- libchisel/src/imports.rs
- libchisel/src/lib.rs
- libchisel/src/remapimports.rs
- libchisel/src/remapstart.rs
- libchisel/src/trimexports.rs
- libchisel/src/trimstartfunc.rs
- libchisel/src/verifyexports.rs
- libchisel/src/verifyimports.rs
> Change ModulePreset to return ModuleError

- libchisel/src/trimexports.rs
When the trait was introduced possibly only the ExportWhitelist was updated.
> Use ModulePreset trait in TrimExports

- CHANGELOG.md
> Update changelog for 0.6.0
